### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by naivefaith** [GraphSAINT/GraphSAINT#14]
hello,i run your model on ppi and flickr.it seems that have some problems.i hope you can alter the code as a elegant style.
my os is win10.
saveing model:
i use timestamp as file name will throw an OSError,i use a nomal string and training succeed.
#---------------------
  Saving model ...
Traceback (most recent call last):
  File "D:\my soft\python374\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\my soft\python374\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\train.py", line 101, in <module>
    train(train_phases, model, minibatch, minibatch_eval, model_eval)
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\train.py", line 80, in train
    torch.save(model.state_dict(), path_saver)
  File "D:\my soft\python374\lib\site-packages\torch\serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "D:\my soft\python374\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\my soft\python374\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: './pytorch_models/saved_model_2020-04-12 14:35:13.pkl'

traget type:
i add "labels = labels.long()" before ”models.py，line 82”，but i not sure that it will not cause other problem run on other dataset.
#---------------------
Traceback (most recent call last):
  File "D:\my soft\python374\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\my soft\python374\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\train.py", line 101, in <module>
    train(train_phases, model, minibatch, minibatch_eval, model_eval)
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\train.py", line 72, in train
    loss_val, f1mic_val, f1mac_val = evaluate_full_batch(model_eval, minibatch_eval, mode='val')
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\train.py", line 18, in evaluate_full_batch
    loss,preds,labels = model.eval_step(*minibatch.one_batch(mode=mode))
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\models.py", line 123, in eval_step
    loss = self._loss(preds,labels_converted,norm_loss_subgraph)
  File "G:\GraphSAINT-master\graphsaint\pytorch_version\models.py", line 82, in _loss
    _ls = torch.nn.CrossEntropyLoss(reduction='none')(preds, labels)
  File "D:\my soft\python374\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\my soft\python374\lib\site-packages\torch\nn\modules\loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\my soft\python374\lib\site-packages\torch\nn\functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\my soft\python374\lib\site-packages\torch\nn\functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward

thank you

**Comment by tedzhouhk** [comment]
Hi naivefaith. 

Thanks for pointing out these cross-platform issues.

Issue 1: 
It seems that the file name of the saved model has illegal characters in windows OS. In the latest commit, we have replaced the ':' character with '_'.  We have tested that this is working on windows 10 18363. Please let us know if this fix your issue.

Issue 2:
The default datatype of np.int seems to be int32 on windows. We have enforced that the labels for softmax loss are int64 by changing np.int to np.int64 in line 41 of models.py.
