### ISSUE TITLE
Can not run the code

### ISSUE THREAD

**Issue by wjlpku** [GraphSAINT/GraphSAINT#2]
Hi, when I follow your advice in readme, some errors happen as  follow: 
Traceback (most recent call last):
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/train.py", line 1, in <module>
    from graphsaint.globals import *
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/globals.py", line 30, in <module>
    flags.DEFINE_string('log_dir', '.', 'base directory for logging and saving embeddings')
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/flags.        py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/absl/flags/_defines.py", line 241        , in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/absl/flags/_defines.py", line 82,         in DEFINE
    flag_values, module_name)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/absl/flags/_defines.py", line 104        , in DEFINE_flag
    fv[flag.name] = flag
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line         430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logg        ing, Se

**Comment by GraphSAINT** [comment]
It seems that this is a Tensorflow version issue (https://github.com/tensorflow/tensorflow/issues/30472). 

I have fixed this by wrapping the flag definition in a "try except" block. 

Please check if it works.

**Comment by wjlpku** [comment]
Thanks for your prompt reply.
After I fix this bug, another problem happen, it seems like also a Tensorflow version issue.
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/train.py", line 254, in <module>
    tf.app.run(main=train_main)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py            ", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_m            ain
    sys.exit(main(argv))
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/train.py", line 248, in train_mai            n
    model,minibatch,sess,train_stat,ph_misc_stat,summary_writer = prepare(train_data,train_params,ar            ch_gcn)
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/train.py", line 99, in prepare
    feats, arch_gcn, train_params, adj_full_norm, logging=True)
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/model.py", line 68, in __init__
    self.build(model_pretrain=model_pretrain)
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/model.py", line 104, in build
    dropout=self.placeholders['dropout'], act='I', model_pretrain=model_pretrain_dense)
  File "/home/wangjialin/Community-Detection/GraphSAINT/graphsaint/layers.py", line 88, in __init__
    initializer=tf.contrib.layers.xavier_initializer(),
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/lazy_loade            r.py", line 62, in __getattr__
    module = self._load()
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/lazy_loade            r.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_mod            ule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/__init__.py",             line 41, in <module>
    from tensorflow.contrib import distributions
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/distributions/            __init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/distributions/            python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/__init__            .py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/_            _init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/l            earn/__init__.py", line 40, in <module>
    from tensorflow.contrib.learn.python.learn.experiment import Experiment
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/l            earn/experiment.py", line 39, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu_estimator
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/tpu/__init__.p            y", line 77, in <module>
    from tensorflow.contrib.tpu.python.tpu.tpu_config import *
  File "/home/wangjialin/Lib/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/tpu/python/tpu            /tpu_config.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.tpu.tpu_config import *
ModuleNotFoundError: No module named 'tensorflow_estimator.python.estimator.tpu'
Anything about TPU? Or can you tell me your tf version?

**Comment by GraphSAINT** [comment]
Can you please let us know your tensorflow version? Judging from the error on `rate` and `keep_prob`, it seems like you are using TF 2.0. 

When testing the code, we are running on TF 1.12.0. We are also planning to update the code to support TF 2.0, and we will release the update soon.

For now, you may do the following as a quick fix:

1. Since the error seems to root from the `Dense` layer, we may replace it with `HighOrderAggregator` layer. Note that a dense layer is equivalent to an order-0 aggregator layer. 

So please go to `./graphsaint/model.py` and replace lines 103 to 105 with 
```
self.layer_pred = layers.HighOrderAggregator(_dim_final,self.num_classes,act='I',order=0,model_pretrain=model_pretrain_dense,dropout=self.placeholders['dropout'],bias='bias')
self.node_preds = self.layer_pred((self.outputs,None,None,None,None))
```

It should produce exactly the same training result.

2. **If you are using TF 2.0**, you need to do one more thing, since the API of `tf.nn.dropout` has changed. 

Go to `./graphsaint/layers.py` and replace every occurrence of `1-self.dropout` with `self.dropout`. 

Please let us know if it works.

**Comment by GraphSAINT** [comment]
Ok, thanks. We'll look into this. We are not using TPU, so not sure why this error popped out. 

Meanwhile, can you check if step 1 (replace dense layer with order-0 aggregator layer) works?

**Comment by GraphSAINT** [comment]
It seems that we can just rename the flag name from `log_dir` to something else to avoid the conflict. 

I have pushed a fix, please check (you may still need to keep you step 1 modification).

**Comment by wjlpku** [comment]
Thanks for your advice, It works !

**Comment by GraphSAINT** [comment]
No problem at all. Glad that it works!
