### ISSUE TITLE
Error: Cannot use GPU when output.shape[1] * nnz(a) > 2^31

### ISSUE THREAD

**Issue by omgmax** [GraphSAINT/GraphSAINT#24]
When I run 
`python -m graphsaint.tensorflow_version.train --data_prefix=./data/ogbn-product/ --train_config=./train_config/open_graph_benchmark/ogbn-products_3_e_gat.yml --gpu=1`

I get the following error:
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/raid/graphs/GraphSAINT/graphsaint/utils.py:112: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  train_config = yaml.load(f_train_config)
Loading training data..
Done loading training data..
/raid/graphs/GraphSAINT/graphsaint/utils.py:190: RuntimeWarning: divide by zero encountered in true_divide
  norm_diag = sp.dia_matrix((1/D,0),shape=diag_shape)
>> layer attentionaggregator_1, dim: [100,256]
>> layer attentionaggregator_2, dim: [256,256]
>> layer attentionaggregator_3, dim: [256,256]
>> layer highorderaggregator_1, dim: [256,47]
WARNING:tensorflow:From /raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py:127: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-10-21 14:37:55.577976: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-10-21 14:37:56.899292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:07:00.0
totalMemory: 31.72GiB freeMemory: 31.41GiB
2020-10-21 14:37:56.899353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-10-21 14:37:57.503937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-21 14:37:57.503971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-10-21 14:37:57.503980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-10-21 14:37:57.526776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30475 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
/raid/graphs/GraphSAINT/graphsaint/graph_samplers.py:168: RuntimeWarning: divide by zero encountered in true_divide
  self.adj_train_norm = scipy.sparse.dia_matrix((1 / self.deg_train, 0), shape=adj_train.shape).dot(adj_train)
sampling 200 subgraphs:   time = 3.898 sec
START PHASE    0
Epoch    0
Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[{{node attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul}} = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_adj_subgraph_0/indices_0_3/_355, attentionaggregator_1/mul_12, _arg_adj_subgraph_0/shape_0_4/_413, attentionaggregator_1/MatMul_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 244, in <module>
    tf.app.run(main=train_main)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 239, in train_main
    ret = train(train_phases,model,minibatch,sess,train_stat,ph_misc_stat,summary_writer)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 192, in train
    evaluate_full_batch(sess_eval,model,minibatch,many_runs_timeline,mode='val')
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 53, in evaluate_full_batch
    preds,loss = sess.run([model.preds, model.loss], feed_dict=feed_dict)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[node attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul (defined at /raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py:282)  = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_adj_subgraph_0/indices_0_3/_355, attentionaggregator_1/mul_12, _arg_adj_subgraph_0/shape_0_4/_413, attentionaggregator_1/MatMul_1)]]

Caused by op 'attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul', defined at:
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 244, in <module>
    tf.app.run(main=train_main)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 238, in train_main
    model,minibatch,sess,train_stat,ph_misc_stat,summary_writer = prepare(train_data,train_params,arch_gcn)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 98, in prepare
    feats, arch_gcn, train_params, adj_full_norm, logging=True)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py", line 66, in __init__
    self.build()
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py", line 89, in build
    _outputs_l = self.aggregate_subgraph()
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py", line 165, in aggregate_subgraph
    hidden = self.aggregators[layer]((hidden,adj,self.dims_feat[layer],_adj_partition_list,self.dim0_adj_sub))
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py", line 61, in __call__
    outputs = self._call(inputs)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py", line 282, in _call
    ret_neigh_i = self.act(tf.sparse_tensor_dense_matmul(adj_weighted,vw_neigh[i]) \
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py", line 2004, in sparse_tensor_dense_matmul
    adjoint_b=adjoint_b)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/ops/gen_sparse_ops.py", line 2789, in sparse_tensor_dense_mat_mul
    name=name)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[node attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul (defined at /raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py:282)  = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_adj_subgraph_0/indices_0_3/_355, attentionaggregator_1/mul_12, _arg_adj_subgraph_0/shape_0_4/_413, attentionaggregator_1/MatMul_1)]]

(graphs) ray@node9:/raid/graphs/GraphSAINT$ python -m graphsaint.tensorflow_version.train --data_prefix=./data/ogbn-product/ --train_config=./train_config/open_graph_benchmark/ogbn-products_3_e_gat.yml --gpu=1
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/raid/graphs/GraphSAINT/graphsaint/utils.py:112: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  train_config = yaml.load(f_train_config)
Loading training data..
Done loading training data..
/raid/graphs/GraphSAINT/graphsaint/utils.py:190: RuntimeWarning: divide by zero encountered in true_divide
  norm_diag = sp.dia_matrix((1/D,0),shape=diag_shape)
>> layer attentionaggregator_1, dim: [100,256]
>> layer attentionaggregator_2, dim: [256,256]
>> layer attentionaggregator_3, dim: [256,256]
>> layer highorderaggregator_1, dim: [256,47]
WARNING:tensorflow:From /raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py:127: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-10-21 14:45:08.221100: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-10-21 14:45:09.020378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:07:00.0
totalMemory: 31.72GiB freeMemory: 31.41GiB
2020-10-21 14:45:09.020423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-10-21 14:45:09.645754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-21 14:45:09.645805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-10-21 14:45:09.645813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-10-21 14:45:09.646048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30475 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
/raid/graphs/GraphSAINT/graphsaint/graph_samplers.py:168: RuntimeWarning: divide by zero encountered in true_divide
  self.adj_train_norm = scipy.sparse.dia_matrix((1 / self.deg_train, 0), shape=adj_train.shape).dot(adj_train)
sampling 200 subgraphs:   time = 3.222 sec
START PHASE    0
Epoch    0
Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[{{node attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul}} = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_adj_subgraph_0/indices_0_3/_355, attentionaggregator_1/mul_12, _arg_adj_subgraph_0/shape_0_4/_413, attentionaggregator_1/MatMul_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 244, in <module>
    tf.app.run(main=train_main)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 239, in train_main
    ret = train(train_phases,model,minibatch,sess,train_stat,ph_misc_stat,summary_writer)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 192, in train
    evaluate_full_batch(sess_eval,model,minibatch,many_runs_timeline,mode='val')
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 53, in evaluate_full_batch
    preds,loss = sess.run([model.preds, model.loss], feed_dict=feed_dict)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[node attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul (defined at /raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py:282)  = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_adj_subgraph_0/indices_0_3/_355, attentionaggregator_1/mul_12, _arg_adj_subgraph_0/shape_0_4/_413, attentionaggregator_1/MatMul_1)]]

Caused by op 'attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul', defined at:
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 244, in <module>
    tf.app.run(main=train_main)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 238, in train_main
    model,minibatch,sess,train_stat,ph_misc_stat,summary_writer = prepare(train_data,train_params,arch_gcn)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/train.py", line 98, in prepare
    feats, arch_gcn, train_params, adj_full_norm, logging=True)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py", line 66, in __init__
    self.build()
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py", line 89, in build
    _outputs_l = self.aggregate_subgraph()
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/model.py", line 165, in aggregate_subgraph
    hidden = self.aggregators[layer]((hidden,adj,self.dims_feat[layer],_adj_partition_list,self.dim0_adj_sub))
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py", line 61, in __call__
    outputs = self._call(inputs)
  File "/raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py", line 282, in _call
    ret_neigh_i = self.act(tf.sparse_tensor_dense_matmul(adj_weighted,vw_neigh[i]) \
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py", line 2004, in sparse_tensor_dense_matmul
    adjoint_b=adjoint_b)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/ops/gen_sparse_ops.py", line 2789, in sparse_tensor_dense_mat_mul
    name=name)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/ray/miniconda3/envs/graphs/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[node attentionaggregator_1/SparseTensorDenseMatMul_4/SparseTensorDenseMatMul (defined at /raid/graphs/GraphSAINT/graphsaint/tensorflow_version/layers.py:282)  = SparseTensorDenseMatMul[T=DT_FLOAT, Tindices=DT_INT64, adjoint_a=false, adjoint_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_adj_subgraph_0/indices_0_3/_355, attentionaggregator_1/mul_12, _arg_adj_subgraph_0/shape_0_4/_413, attentionaggregator_1/MatMul_1)]]

**Comment by tedzhouhk** [comment]
Hi omgmax, the error is because Tensorflow does not support indexing on GPU with 64 bit integer. You can try the following options to avoid this problem
1. use the pytorch version with "python -m graphsaint.pytorch_version.train ..."
2. use the flag "--cpu_eval" to perform evaluation on CPU instead of GPU
3. we manually partition the adjacency matrix into 8 parts, you can increase this number to make sure output.shape[1] * nnz(a) < 2^31. Specifically, you would need to modify the code in: https://github.com/GraphSAINT/GraphSAINT/blob/a051742ff2de4094c97eb523d7108a4fc1d22739/graphsaint/tensorflow_version/minibatch.py#L37
https://github.com/GraphSAINT/GraphSAINT/blob/a051742ff2de4094c97eb523d7108a4fc1d22739/graphsaint/tensorflow_version/model.py#L35
https://github.com/GraphSAINT/GraphSAINT/blob/a051742ff2de4094c97eb523d7108a4fc1d22739/graphsaint/tensorflow_version/model.py#L161

**Comment by omgmax** [comment]
Thank you I will try that
